import { Fragment, useState } from 'react';
import { Card, CardHeader, CardContent, CardTitle } from '@/components/ui/card';
import { Textarea } from '@/components/ui/textarea';
import { Button } from '@/components/ui/button';
import { Loader2, MessageCircle, ArrowLeft, Send } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { MenuLabel } from '@/components';
import { toast } from 'sonner';

const BACKEND_URL = import.meta.env.VITE_BACKEND_URL;

/* ------------------ Domain Data ------------------ */
const domainData: Record<string, { q: string; a: string }[]> = {
  "Letter of Credit (UCP 600)": [
    {
      q: "Under UCP 600, what constitutes a compliant presentation of documents, and how does the principle of strict compliance interact with the doctrine of substantial compliance in international trade finance?",
      a: "Under UCP 600, a compliant presentation requires documents to be presented within the validity period of the credit, at the designated place, and in accordance with the terms and conditions of the credit. Article 14(a) mandates that banks examine documents to determine whether they appear on their face to constitute a compliant presentation. The principle of strict compliance requires that documents must strictly conform to the terms of the LC - any discrepancy, however minor, can justify refusal. However, Article 14(d) provides that data in documents need not be identical but must not conflict. The doctrine of substantial compliance is generally not accepted in LC practice; banks are not required to look beyond the face of documents or consider commercial reasonableness. This strict approach protects banks from liability while ensuring predictability in international trade transactions.",
    },
    {
      q: "How does the independence principle under UCP 600 affect the relationship between the underlying sales contract and the letter of credit, particularly in cases of alleged fraud or breach of contract?",
      a: "The independence principle, codified in UCP 600 Article 4, establishes that credits are separate transactions from the underlying sales contracts. Banks deal with documents, not goods, services, or performance. This means that even if the buyer alleges fraud or breach of contract by the seller, the issuing bank is generally obligated to honor a compliant presentation. The only recognized exception is the fraud exception, where the beneficiary's fraud is clear and obvious (fraud in the documents or fraud in the underlying transaction). Courts have held that banks may refuse payment only when fraud is established to the bank's knowledge before payment. This principle ensures the commercial utility of LCs as reliable payment mechanisms while balancing against fraudulent abuse.",
    },
    {
      q: "What are the obligations and liabilities of a confirming bank versus an advising bank under UCP 600, and how do these roles impact the risk allocation in a documentary credit transaction?",
      a: "Under UCP 600, an advising bank (Article 9) has a duty to verify the apparent authenticity of the credit and advise it accurately. The advising bank assumes no liability to honor or negotiate the credit. In contrast, a confirming bank (Article 8) adds its definite undertaking to honor or negotiate a compliant presentation, in addition to the issuing bank's undertaking. The confirming bank assumes the same obligations as the issuing bank and is irrevocably bound from the time it adds its confirmation. This significantly impacts risk allocation: the beneficiary gains protection against both commercial risk (issuing bank's ability to pay) and country risk (political or transfer restrictions in the issuing bank's country). The confirming bank bears the risk of the issuing bank's failure to reimburse, making confirmation fees reflective of the perceived risk of the issuing bank and its jurisdiction.",
    },
    {
      q: "How do the examination standards under UCP 600 Article 14 apply to transport documents, and what are the implications of discrepancies in bills of lading for the beneficiary's right to payment?",
      a: "UCP 600 Article 14 requires banks to examine documents within a maximum of five banking days following the day of presentation. For transport documents, Articles 19-25 specify detailed requirements. A bill of lading must appear to indicate the name of the carrier, be signed by the carrier or master or their agent, indicate shipment from the port of loading to the port of discharge stated in the credit, and be the sole original or full set if issued in more than one original. Common discrepancies include late shipment dates, incorrect ports, goods descriptions not matching the credit, and missing signatures or endorsements. Any discrepancy entitles the issuing bank to refuse documents under Article 16. The beneficiary's right to payment is contingent on presenting compliant documents; discrepancies must be waived by the applicant or corrected within the presentation period to preserve payment rights.",
    },
    {
      q: "Explain the concept of 'honour' under UCP 600 and how it differs for sight credits, deferred payment credits, and acceptance credits. What are the implications for the beneficiary's access to funds?",
      a: "Under UCP 600 Article 2, 'honour' means: (a) to pay at sight if the credit is available by sight payment; (b) to incur a deferred payment undertaking and pay at maturity if the credit is available by deferred payment; (c) to accept a bill of exchange drawn by the beneficiary and pay at maturity if the credit is available by acceptance. For sight credits, the beneficiary receives immediate payment upon compliant presentation. For deferred payment credits, the bank incurs an irrevocable undertaking to pay at a specified future date, giving the beneficiary certainty but delayed access to funds. For acceptance credits, the beneficiary receives an accepted draft which can potentially be discounted in the market for immediate liquidity. The choice of availability affects the beneficiary's cash flow, financing costs, and risk exposure, with sight credits providing the most immediate access to funds but potentially at higher costs to the applicant.",
    },
    {
      q: "Under UCP 600, what is the effect of amendments to a letter of credit, and how should partial acceptance of amendments be handled by the beneficiary and the banks involved?",
      a: "Under UCP 600 Article 10, an amendment is effective when advised to the beneficiary, but the beneficiary must communicate acceptance or rejection. Until the beneficiary communicates acceptance, the original credit terms remain in force. Critically, Article 10(c) states that partial acceptance of an amendment is not allowed and will be deemed notification of rejection. This prevents confusion about which terms apply. The beneficiary should communicate acceptance by presenting documents in compliance with the amendment or by separate notification. Banks must ensure amendments are properly advised and track the status of each amendment. If the beneficiary remains silent, the original terms continue to govern, but presentation of documents complying with the amendment constitutes acceptance. This framework ensures clarity and prevents disputes about applicable terms.",
    },
    {
      q: "How does UCP 600 address the issue of original documents versus copies, and what are the banking practices regarding documents marked as 'original' or bearing signatures, stamps, or labels?",
      a: "UCP 600 Article 17 addresses original documents. A bank treats as original any document bearing an apparently original signature, mark, stamp, or label of the issuer, unless the document itself indicates it is not an original. A document requirement for an original may also be satisfied by presentation of the sole original or first of multiple originals. Documents produced by reprographic, automated, or computerized systems, or as carbon copies, may be accepted as originals if marked as original or appear to be signed. ISBP 745 provides additional guidance, clarifying that documents need not be titled 'original' if they appear to be the original. Banks examine documents on their face without requiring proof of originality beyond apparent compliance. This practical approach accommodates modern document production methods while maintaining documentary credit integrity.",
    },
    {
      q: "What are the key differences between transferable credits under UCP 600 Article 38 and back-to-back letters of credit, and what are the risk considerations for intermediary traders using each structure?",
      a: "A transferable credit (UCP 600 Article 38) allows the first beneficiary (middleman) to request the transferring bank to make the credit available to one or more second beneficiaries. Key features include: the credit must be expressly designated as transferable; it can only be transferred on the terms stated in the original credit with certain permitted variations (amount, unit price, expiry date, presentation period, latest shipment date); and the first beneficiary may substitute its own invoices. Back-to-back credits involve two separate credits: the original credit in favor of the middleman, and a second credit opened by the middleman's bank in favor of the supplier. Risk considerations differ significantly: in transferable credits, the middleman's margin is protected through invoice substitution but exposure is limited; in back-to-back arrangements, the middleman's bank takes independent credit risk on the second credit, and timing mismatches between the two credits can create significant exposure.",
    },
    {
      q: "How do standby letters of credit differ from commercial documentary credits under UCP 600 and ISP98, and what are the typical circumstances triggering payment under a standby credit?",
      a: "While both standby LCs and commercial documentary credits can be governed by UCP 600, standbys are more commonly subject to ISP98 (International Standby Practices). Commercial documentary credits are designed to be drawn upon in the normal course of business - the beneficiary presents shipping documents to receive payment for goods shipped. Standby credits, conversely, serve as backup payment mechanisms; drawing occurs only when the applicant fails to perform an underlying obligation. Typical triggers include: non-payment of invoices, failure to deliver goods or services, breach of contract terms, or default on loan obligations. The documentary requirements for standbys are typically simpler - often just a demand statement and possibly a certificate of default. ISP98 provides rules specifically tailored to standby practices, including provisions for automatic extension clauses, syndication, and transfer that differ from UCP 600 approaches.",
    },
    {
      q: "Under UCP 600, how should banks handle documents presented with discrepancies, and what is the process for seeking waiver from the applicant while protecting all parties' interests?",
      a: "When banks identify discrepancies under UCP 600 Article 16, they must provide a single notice to the presenter within five banking days, specifying each discrepancy and stating whether they are holding documents pending further instructions, returning documents, or acting according to prior instructions. The notice must state the bank's refusal to honour or negotiate. Banks commonly contact the applicant to seek waiver of discrepancies. If the applicant waives discrepancies, the bank may honour the presentation. However, the bank retains discretion - it is not obligated to seek waiver or to honour even if waiver is given. The applicant's waiver does not affect the bank's right to claim reimbursement from the applicant. Time is critical: failure to provide proper notice within five banking days precludes the bank from claiming non-compliance. This process balances commercial flexibility with documentary credit certainty.",
    },
  ],

  "Bills of Exchange & Discounting": [
    {
      q: "What are the essential elements of a valid bill of exchange under the Bills of Exchange Act, and how do defects in these elements affect the negotiability and enforceability of the instrument?",
      a: "A valid bill of exchange must contain: (1) an unconditional order in writing; (2) addressed by one person (drawer) to another (drawee); (3) signed by the drawer; (4) requiring the drawee to pay on demand or at a fixed or determinable future time; (5) a sum certain in money; (6) to or to the order of a specified person, or to bearer. Defects in these elements can render the instrument invalid or affect its negotiability. For example, a conditional order creates uncertainty and destroys negotiability. If the sum is not certain (e.g., subject to fluctuating exchange rates without a fixed mechanism), the instrument may not qualify as a bill. Missing signatures or alterations without proper authentication can make the bill unenforceable. However, minor irregularities may not invalidate the bill if the essential character is preserved. Holders in due course receive protection against certain defects, but fundamental invalidity cannot be cured by negotiation.",
    },
    {
      q: "Explain the process of bill discounting and the legal relationship between the discounting bank, the drawer, and the drawee. How does recourse affect the risk allocation in bill discounting transactions?",
      a: "Bill discounting involves a bank purchasing a bill of exchange before maturity at a discount, providing immediate liquidity to the holder. The discount represents the bank's compensation for advancing funds and assuming risk until maturity. The legal relationships are: the drawer creates the bill and may be the original discounter; the drawee/acceptor has primary liability to pay at maturity; the discounting bank becomes a holder and can enforce the bill against all prior parties. Recourse refers to the bank's right to recover from the discounter if the bill is dishonored. With recourse discounting, if the drawee fails to pay, the bank can claim from the drawer/endorser who discounted the bill. Without recourse (or non-recourse) discounting, the bank assumes the credit risk of the drawee and cannot claim back from the discounter. Non-recourse discounting commands higher discount rates reflecting the additional risk assumed by the bank.",
    },
    {
      q: "How does the concept of 'holder in due course' under bills of exchange law protect parties in trade finance transactions, and what are the requirements to achieve this status?",
      a: "A holder in due course (HDC) receives enhanced protection under bills of exchange law, taking the bill free from defects in title of prior parties and free from personal defenses available against prior holders. To qualify as HDC, a person must: (1) be a holder of a bill that is complete and regular on its face; (2) have taken the bill before it was overdue and without notice of prior dishonor; (3) have taken in good faith and for value; (4) have had no notice of any defect in the title of the person who negotiated it. In trade finance, HDC status protects banks that discount bills in good faith, ensuring they can enforce payment even if disputes exist between the original parties. This protection is essential for the marketability of bills and the functioning of the discount market. However, HDC status does not protect against real defenses such as forgery, material alteration, or incapacity.",
    },
    {
      q: "What is the difference between a clean bill and a documentary bill in trade finance, and how do these distinctions affect the security and risk profile of the financing arrangement?",
      a: "A clean bill is a bill of exchange not accompanied by shipping or title documents - it represents a pure payment obligation. A documentary bill is accompanied by documents of title (typically bills of lading, insurance certificates, and commercial invoices) that control the goods. The security implications are significant: with documentary bills, the bank holding the documents controls access to the goods until payment or acceptance, providing security for the financing. Clean bills rely solely on the creditworthiness of the parties without documentary security. Documentary bills are commonly used in documentary collections (D/P - documents against payment, or D/A - documents against acceptance) where the collecting bank releases documents only upon payment or acceptance. The risk profile differs accordingly: documentary bills offer goods as implicit security, while clean bills expose the holder to unsecured credit risk. Discount rates and financing terms reflect these risk differences.",
    },
    {
      q: "Explain the liability of an acceptor, drawer, and endorser of a bill of exchange. How does the chain of liability work when a bill is dishonored at maturity?",
      a: "The acceptor bears primary liability on a bill of exchange - by accepting, the drawee undertakes to pay according to the tenor of acceptance. The drawer has secondary liability, warranting that the bill will be accepted and paid, and undertaking to compensate any holder if it is dishonored (provided proper proceedings on dishonor are taken). Each endorser also incurs secondary liability to subsequent holders, warranting the bill and undertaking to compensate if dishonored. When a bill is dishonored at maturity, the holder must give notice of dishonor to parties against whom recourse is sought (failure to give notice may discharge those parties). The holder can then proceed against any or all liable parties - the acceptor, drawer, and endorsers are jointly and severally liable. The holder may choose to sue the party most likely to pay. A party who pays has rights of recourse against prior parties. This chain of liability provides multiple sources of payment, enhancing the bill's creditworthiness.",
    },
    {
      q: "How does the avalisation (bank guarantee on a bill) work in international trade finance, and what are the legal implications for the avalising bank and other parties to the bill?",
      a: "Avalisation is a form of guarantee where a bank (the avalist) adds its undertaking to a bill of exchange, typically by signing on the face of the bill with words such as 'per aval' or 'good as aval.' The avalist guarantees payment of the bill, usually for a specific party (drawer, acceptor, or endorser). The legal implications are: the avalist is liable in the same manner as the party for whom the aval is given; the avalist's liability is independent and survives even if the guaranteed party's obligation is void (except for formal defects); upon paying the bill, the avalist acquires rights against the party guaranteed and all parties liable to that party. For banks, avalisation creates a direct, unconditional liability on the bill, making it more marketable and easier to discount. The avalised bill carries the credit standing of the avalising bank, significantly reducing credit risk for holders and facilitating trade finance at better rates.",
    },
    {
      q: "What are the implications of presenting a bill of exchange for acceptance versus presenting it directly for payment? How does this affect the rights and obligations of the parties?",
      a: "Presentment for acceptance is required for bills payable at a fixed period after sight (to fix the maturity date) and is optional for other time bills. Upon acceptance, the drawee becomes the acceptor with primary liability. If acceptance is refused, the bill is dishonored by non-acceptance, and the holder has immediate recourse against the drawer and endorsers without waiting for maturity. Presentment for payment occurs at maturity for time bills or on demand for sight bills. The implications differ: acceptance creates a binding obligation before maturity, allowing the holder to assess creditworthiness and potentially discount the bill; refusal of acceptance provides early warning of potential non-payment. For the drawer, acceptance shifts primary liability to the acceptor. For the holder, an accepted bill is more valuable and marketable than an unaccepted bill. Failure to present for payment at the proper time may discharge endorsers and, in some cases, the drawer, though the acceptor remains liable.",
    },
    {
      q: "How do forfaiting transactions differ from traditional bill discounting, and what are the key features that make forfaiting attractive for medium-term trade finance?",
      a: "Forfaiting is a form of trade finance where the forfaiter purchases, without recourse, receivables (typically bills of exchange or promissory notes) arising from export transactions. Key differences from traditional discounting include: (1) forfaiting is always without recourse - the forfaiter assumes all commercial and political risk; (2) forfaiting typically involves medium to long-term receivables (180 days to 7 years), while traditional discounting focuses on short-term bills; (3) forfaited instruments are usually avalised by a bank in the importer's country, providing bank credit risk rather than corporate risk; (4) forfaiting commonly involves emerging market transactions where political risk is significant. Attractive features include: complete risk transfer to the forfaiter; fixed-rate financing eliminating interest rate risk; off-balance sheet treatment for the exporter; simplified administration as the forfaiter handles collection. The forfaiting market provides liquidity for medium-term trade receivables that might otherwise be difficult to finance.",
    },
    {
      q: "What is the role of protest in bills of exchange, and under what circumstances is protest required or excused? How does protest affect the holder's rights against parties to the bill?",
      a: "Protest is a formal notarial act evidencing dishonor of a bill of exchange. It serves as official proof that presentment was made and the bill was dishonored. Protest is required for foreign bills (bills drawn in one country and payable in another) to preserve recourse against the drawer and endorsers. For inland bills, protest is generally optional but may be required by the terms of the bill. Protest is excused when: it is waived by the parties; the drawee is dead or bankrupt; presentment is excused; or delay is caused by circumstances beyond the holder's control. The effect of protest (or its absence when required) is significant: failure to protest a foreign bill when required discharges the drawer and endorsers from liability. Protest provides conclusive evidence of dishonor in legal proceedings. The protest must be made by a notary public at the place of dishonor, noting the date, reasons for dishonor, and demand made. Noting (a preliminary step) may preserve rights pending formal protest.",
    },
    {
      q: "How does the Uniform Rules for Collections (URC 522) govern documentary collections, and what are the responsibilities of the remitting bank and collecting bank in a D/P or D/A transaction?",
      a: "URC 522 provides standardized rules for documentary collections, where banks act as agents to obtain payment or acceptance against delivery of documents. In a D/P (documents against payment) collection, the collecting bank releases documents only upon payment. In D/A (documents against acceptance), documents are released upon acceptance of a bill of exchange. The remitting bank's responsibilities include: ensuring the collection instruction is complete and unambiguous; forwarding documents and instructions to the collecting bank; and advising the principal of the collection's progress. The collecting bank must: present documents as instructed; obtain payment or acceptance as required; protect the goods if instructed and payment/acceptance is refused; and remit proceeds promptly. Importantly, banks have no obligation to examine documents beyond verifying they appear to be as listed. Banks assume no liability for the genuineness, validity, or legal effect of documents. URC 522 clarifies that banks act only as agents and do not assume payment obligations, distinguishing collections from letters of credit.",
    },
  ],

  "Bank Guarantees & Standby LCs": [
    {
      q: "What are the key differences between a bank guarantee governed by URDG 758 and a standby letter of credit governed by ISP98, and how do these differences affect the beneficiary's rights and the bank's obligations?",
      a: "URDG 758 (Uniform Rules for Demand Guarantees) and ISP98 (International Standby Practices) both govern independent undertakings, but with different approaches. Key differences include: (1) Examination period - URDG 758 allows 5 business days for examination, while ISP98 provides a reasonable time not exceeding 7 business days; (2) Extend or pay provisions - URDG 758 Article 23 specifically addresses extend or pay demands, while ISP98 treats these under general rules; (3) Transfer - URDG 758 requires guarantor consent for transfer, while ISP98 allows transfer of drawing rights without consent unless prohibited; (4) Terminology - URDG uses 'guarantee' terminology familiar in civil law jurisdictions, while ISP98 uses 'standby' terminology common in US practice. For beneficiaries, both provide strong independent payment rights upon compliant demand. Banks under both rules examine only documentary compliance without investigating underlying facts. The choice between instruments often depends on jurisdictional preferences, with guarantees preferred in Europe and Middle East, and standbys in North America.",
    },
    {
      q: "Explain the independence principle in demand guarantees and how it interacts with the underlying contract. Under what circumstances can a bank refuse to pay despite a compliant demand?",
      a: "The independence principle establishes that a demand guarantee is a separate undertaking from the underlying contract between the applicant and beneficiary. The guarantor's obligation to pay arises solely from the terms of the guarantee and a compliant demand, regardless of disputes in the underlying contract. URDG 758 Article 5 explicitly states that guarantees are independent of the underlying relationship. A bank can refuse payment only in limited circumstances: (1) the demand does not comply with the guarantee terms; (2) the demand is made after expiry; (3) fraud or abuse of right is manifest and clear to the bank (the fraud exception). Courts have narrowly interpreted the fraud exception, requiring clear evidence of fraud known to the bank before payment. Mere allegations of breach or disputes do not justify refusal. This independence is essential for the commercial utility of guarantees - beneficiaries rely on certain payment upon compliant demand, and banks avoid being drawn into underlying disputes. The principle protects the guarantee's function as a reliable security instrument.",
    },
    {
      q: "What are the different types of bank guarantees commonly used in international trade and construction projects, and what specific risks does each type address?",
      a: "Common types of bank guarantees include: (1) Bid/Tender Guarantee - ensures the bidder will enter into the contract if awarded and not withdraw the bid; typically 2-5% of bid value; addresses the risk of bid withdrawal. (2) Performance Guarantee - ensures the contractor will perform contractual obligations; typically 10-15% of contract value; addresses performance risk. (3) Advance Payment Guarantee - secures repayment of advance payments if the contractor fails to perform; covers the advance amount; addresses the risk of advance misappropriation. (4) Retention Money Guarantee - allows release of retention money while guaranteeing defect rectification; addresses quality/defect risk. (5) Payment Guarantee - ensures the buyer will pay for goods/services; addresses credit risk of the buyer. (6) Warranty Guarantee - covers the warranty period obligations; addresses post-completion defect risk. Each guarantee type is tailored to specific project phases and risks, with terms, amounts, and validity periods reflecting the underlying risk profile.",
    },
    {
      q: "How does the counter-guarantee structure work in international guarantee transactions, and what are the relationships and obligations between the instructing party, counter-guarantor, and local guarantor?",
      a: "In international transactions, a counter-guarantee structure involves multiple banks to provide a local guarantee in the beneficiary's country. The structure typically works as follows: (1) The applicant requests their bank (instructing party/counter-guarantor) to arrange a guarantee; (2) The counter-guarantor issues a counter-guarantee to a bank in the beneficiary's country (local guarantor); (3) The local guarantor issues the guarantee to the beneficiary based on the counter-guarantee. The relationships are: the local guarantor's obligation to the beneficiary is independent and governed by the guarantee terms; the counter-guarantor's obligation to the local guarantor is governed by the counter-guarantee; the applicant's obligation to the counter-guarantor is governed by their agreement. Under URDG 758, the counter-guarantee is also an independent undertaking. When the beneficiary makes a demand, the local guarantor pays and claims under the counter-guarantee; the counter-guarantor pays and claims from the applicant. This structure provides beneficiaries with a local bank relationship while allowing applicants to use their relationship bank.",
    },
    {
      q: "What are the requirements for a compliant demand under URDG 758, and how should the supporting statement be drafted to ensure payment?",
      a: "Under URDG 758, a compliant demand must: (1) be made in documentary form (paper or electronic as permitted); (2) be signed if the guarantee requires signature; (3) be made at the place of presentation specified in the guarantee; (4) be made before expiry; (5) include a supporting statement as required by Article 15. The supporting statement must indicate in what respect the applicant is in breach of its obligations under the underlying relationship. This statement need not be detailed - a simple statement that the applicant has failed to perform its obligations is typically sufficient. The guarantor examines only whether the statement appears to comply with the guarantee terms; it does not investigate the truth of the statement. To ensure payment, the demand should: clearly identify the guarantee by number and date; state the amount demanded; include the required supporting statement using language that mirrors the guarantee terms; be presented within validity; and comply with any specific documentary requirements in the guarantee. Beneficiaries should carefully review guarantee terms before making demands.",
    },
    {
      q: "How do reduction clauses and expiry mechanisms work in bank guarantees, and what are the implications for the beneficiary's security and the applicant's exposure?",
      a: "Reduction clauses allow the guarantee amount to decrease over time or upon occurrence of specified events, reflecting reduced exposure as the underlying contract progresses. Common mechanisms include: (1) automatic reductions on specified dates or upon presentation of specified documents (e.g., progress certificates); (2) reductions upon partial performance milestones; (3) reductions linked to retention release. Expiry mechanisms define when the guarantee terminates: (1) fixed expiry date - guarantee expires on a specified date; (2) expiry upon event - guarantee expires upon occurrence of specified event (e.g., issuance of final acceptance certificate); (3) open-ended with reduction - no fixed expiry but reducing amounts. For beneficiaries, reduction clauses may reduce security below actual exposure if reductions don't match actual risk reduction. Beneficiaries should ensure reduction triggers accurately reflect performance milestones. For applicants, reduction clauses reduce guarantee fees and credit line utilization as exposure decreases. URDG 758 Article 25 addresses expiry, requiring demands to be made before the expiry date and time at the place of presentation.",
    },
    {
      q: "What is the 'extend or pay' demand mechanism under URDG 758, and how should banks and beneficiaries handle such demands?",
      a: "The 'extend or pay' mechanism allows a beneficiary to demand either extension of the guarantee or payment of the guarantee amount. Under URDG 758 Article 23, when a beneficiary makes such a demand, the guarantor must: (1) promptly inform the instructing party (or counter-guarantor); (2) suspend payment for a period not exceeding 30 calendar days to allow the instructing party to arrange extension or authorize payment. If no extension is arranged within this period, the guarantor must pay. This mechanism protects beneficiaries when the underlying contract is delayed and the guarantee might expire before completion. For banks, the procedure requires prompt communication with the instructing party and careful tracking of the suspension period. For beneficiaries, the demand must clearly state the alternative (extend or pay) and comply with other demand requirements. The mechanism balances the beneficiary's need for continued security with the applicant's opportunity to arrange extension rather than face immediate payment. It is particularly useful in construction projects where delays are common.",
    },
    {
      q: "How does the assignment of proceeds differ from transfer of a bank guarantee, and what are the legal and practical implications of each for the beneficiary and potential assignees?",
      a: "Assignment of proceeds and transfer of a guarantee are distinct concepts with different implications. Assignment of proceeds means the beneficiary assigns the right to receive payment proceeds to a third party (assignee), but the beneficiary retains the right to make demands under the guarantee. The assignee has no direct rights against the guarantor - they receive proceeds only if the beneficiary makes a compliant demand and payment is made. Transfer of a guarantee means the guarantee itself is transferred to a new beneficiary (transferee) who acquires all rights under the guarantee, including the right to make demands. Under URDG 758 Article 33, transfer requires the guarantor's agreement unless the guarantee states it is transferable. Practical implications: assignment is simpler and doesn't require guarantor consent, but provides weaker security to the assignee; transfer provides the transferee with direct rights but requires guarantor involvement and may involve fees. Assignment is commonly used in financing arrangements where lenders take security over guarantee proceeds, while transfer is used when the beneficiary's role in the underlying contract is transferred to another party.",
    },
    {
      q: "What are the bank's examination standards under URDG 758, and how do these standards protect the bank from liability while ensuring fair treatment of demands?",
      a: "Under URDG 758 Article 19, the guarantor must examine a demand to determine if it appears on its face to be a complying presentation. The examination is limited to documents - the guarantor does not investigate underlying facts or verify the truth of statements in the demand. Article 19(b) specifies that data in documents need not be identical but must not conflict with data in the guarantee or other required documents. The guarantor has 5 business days following presentation to examine and decide. These standards protect banks by: (1) limiting examination to documentary compliance, avoiding involvement in underlying disputes; (2) providing a clear timeframe for decision; (3) establishing objective criteria for compliance. Fair treatment is ensured through: (1) the requirement to examine documents in good faith; (2) the obligation to give notice of rejection specifying all discrepancies (Article 24); (3) the preclusion rule - failure to give timely, compliant notice precludes the guarantor from claiming non-compliance. Banks must balance efficient processing with careful examination to avoid both wrongful payment and wrongful rejection.",
    },
    {
      q: "How do court injunctions and restraining orders affect bank guarantee payments, and what are the considerations for banks when faced with conflicting obligations?",
      a: "Court injunctions can create significant challenges for banks in guarantee transactions. When a court issues an injunction restraining payment, the bank faces conflicting obligations: the independent undertaking to pay upon compliant demand versus the legal requirement to comply with court orders. Considerations include: (1) Jurisdiction - the bank must assess whether the court has jurisdiction over it and whether the order is enforceable; (2) Basis for injunction - courts typically grant injunctions only in cases of clear fraud or where the balance of convenience strongly favors restraint; (3) Timing - injunctions sought after payment cannot reverse completed transactions; (4) Interpleader - banks may seek to interplead, depositing funds with the court and letting parties litigate entitlement; (5) Indemnity - banks may require indemnity from the applicant seeking the injunction. The fraud exception is narrowly construed - mere allegations of breach or disputes are insufficient. Banks generally resist being drawn into underlying disputes and will pay against compliant demands unless fraud is manifest or a valid court order prevents payment. The independence principle is fundamental to guarantee utility and is protected by courts in most jurisdictions.",
    },
  ],

  "Incoterms 2020": [
    {
      q: "How do the risk transfer points differ between FOB, CIF, and DDP under Incoterms 2020, and what are the implications for cargo insurance arrangements in international trade transactions?",
      a: "Under Incoterms 2020, risk transfer points vary significantly: FOB (Free On Board) - risk transfers when goods are placed on board the vessel at the named port of shipment; CIF (Cost, Insurance and Freight) - risk transfers at the same point as FOB (on board at shipment port), despite the seller arranging and paying for insurance and freight to destination; DDP (Delivered Duty Paid) - risk remains with the seller until goods are delivered at the named destination, cleared for import. Insurance implications are critical: under FOB, the buyer bears risk during main carriage and should arrange insurance; under CIF, the seller must obtain minimum insurance (Institute Cargo Clauses C or equivalent) covering at least 110% of contract value, but the buyer bears risk and may want additional coverage; under DDP, the seller bears all risk and should maintain comprehensive insurance throughout transit. Buyers under CIF should understand that despite the seller arranging insurance, they are the risk-bearers and should verify coverage adequacy. The mismatch between cost allocation and risk transfer in CIF often causes confusion.",
    },
    {
      q: "Explain the obligations regarding export and import clearance under different Incoterms 2020 rules. How do these obligations interact with trade compliance and customs regulations?",
      a: "Incoterms 2020 allocates customs clearance obligations as follows: EXW (Ex Works) - buyer responsible for both export and import clearance, though this is often impractical as the seller is better positioned for export formalities; FCA, FAS, FOB, CFR, CIF, CPT, CIP - seller responsible for export clearance, buyer for import clearance; DAP, DPU - seller responsible for export clearance, buyer for import clearance and duties; DDP - seller responsible for both export and import clearance, including all duties and taxes. Trade compliance implications include: export controls and licenses must be obtained by the party responsible for export clearance; import regulations, tariffs, and duties fall on the party responsible for import clearance; both parties must ensure compliance with sanctions, restricted party screening, and documentation requirements. Under DDP, sellers must understand destination country import requirements, which can be complex and risky. The 2020 revision clarified that FCA allows the buyer to instruct their carrier to issue a bill of lading to the seller, addressing a practical need in LC transactions requiring shipped bills of lading.",
    },
    {
      q: "What are the key differences between CPT/CIP and CFR/CIF under Incoterms 2020, and when should each term be used in international trade contracts?",
      a: "CPT (Carriage Paid To) and CIP (Carriage and Insurance Paid To) are multimodal terms suitable for any mode of transport, while CFR (Cost and Freight) and CIF (Cost, Insurance and Freight) are maritime-only terms for port-to-port shipments. Key differences: (1) Mode of transport - CPT/CIP for any mode including containerized cargo; CFR/CIF only for conventional maritime cargo loaded on board vessel; (2) Risk transfer - under CPT/CIP, risk transfers when goods are handed to the first carrier; under CFR/CIF, risk transfers when goods are on board the vessel; (3) Insurance level - CIP requires Institute Cargo Clauses A (all risks), while CIF requires only Institute Cargo Clauses C (minimum coverage). Usage guidance: use CFR/CIF for bulk commodities and conventional cargo loaded directly onto vessels; use CPT/CIP for containerized cargo, multimodal transport, or when goods are handed to carriers at inland points. The 2020 revision's enhanced insurance requirement under CIP (Clauses A vs. C) makes CIP more protective for buyers. Parties should specify the named place of destination clearly, as this determines where the seller must contract carriage to.",
    },
    {
      q: "How does Incoterms 2020 address the allocation of costs between buyer and seller, and what are common disputes regarding cost allocation in international trade?",
      a: "Incoterms 2020 provides detailed cost allocation in the A9/B9 articles of each rule. General principles: the seller bears all costs until the delivery point; the buyer bears costs from delivery onwards; specific costs are allocated based on the term chosen. Common cost allocation includes: packaging (seller), export clearance costs (typically seller except EXW), main carriage (varies by term), insurance (varies), import clearance (typically buyer except DDP), and unloading at destination (varies). Common disputes arise regarding: (1) Terminal handling charges (THC) - often unclear whether included in freight or separately charged; (2) Container detention and demurrage - delays can cause disputes about responsibility; (3) Inspection costs - pre-shipment inspection typically seller's cost, destination inspection typically buyer's; (4) Documentation costs - the party requiring documents typically bears the cost; (5) Unexpected charges - port surcharges, security fees, and similar charges may not be clearly allocated. To minimize disputes, contracts should specify allocation of foreseeable charges beyond the Incoterm itself. The 2020 revision improved clarity on security-related costs and requirements.",
    },
    {
      q: "What is the significance of the 'delivery' concept under Incoterms 2020, and how does it relate to the transfer of risk, the passing of property, and the seller's performance obligations?",
      a: "Under Incoterms 2020, 'delivery' is the point where the seller fulfills its delivery obligation and risk transfers to the buyer. This is distinct from physical receipt by the buyer. Delivery points vary: EXW - goods placed at seller's disposal at named place; FCA - goods handed to carrier or loaded on buyer's vehicle; FAS - goods placed alongside vessel; FOB/CFR/CIF - goods on board vessel; CPT/CIP - goods handed to first carrier; DAP - goods at buyer's disposal on arriving transport; DPU - goods unloaded at destination; DDP - goods at buyer's disposal, cleared for import. Risk transfer coincides with delivery - once delivered, loss or damage is buyer's risk even if seller arranges further carriage. However, Incoterms do not address passing of property (title), which is governed by the sales contract and applicable law. The seller's performance obligations are fulfilled at delivery, though obligations regarding carriage, insurance, and documentation may extend beyond. Understanding the delivery point is crucial for insurance arrangements, as the party bearing risk should ensure adequate coverage from that point.",
    },
    {
      q: "How should Incoterms 2020 be incorporated into sales contracts and letters of credit, and what are the common errors in Incoterm specification that lead to disputes?",
      a: "Proper incorporation requires: (1) stating the chosen Incoterm followed by the named place/port (e.g., 'CIF Shanghai Incoterms 2020'); (2) specifying 'Incoterms 2020' to identify the applicable version; (3) ensuring the named place is precise and appropriate for the chosen term. In letters of credit, the Incoterm should be stated in the goods description or shipment terms, and document requirements should align with the term's obligations. Common errors include: (1) Using maritime terms (FOB, CIF) for containerized cargo - risk transfers at wrong point; (2) Imprecise named places - 'FOB China' is ambiguous; should specify port; (3) Omitting the Incoterms version - creates uncertainty about applicable rules; (4) Mismatching Incoterm and LC requirements - e.g., EXW with LC requiring shipped bill of lading; (5) Using inappropriate terms for the transaction - e.g., DDP where seller cannot handle import clearance; (6) Failing to address costs not covered by Incoterms - terminal charges, inspection fees. Parties should ensure the Incoterm chosen matches their commercial intentions and capabilities, and that all related documents consistently reflect the chosen term.",
    },
    {
      q: "What changes were introduced in Incoterms 2020 compared to Incoterms 2010, and how do these changes affect trade finance and documentary requirements?",
      a: "Key changes in Incoterms 2020 include: (1) FCA and bills of lading - new option allowing buyer to instruct carrier to issue on-board bill of lading to seller, addressing LC requirements for shipped B/Ls when goods are handed to carrier before loading; (2) CIP insurance level - increased from Institute Cargo Clauses C to Clauses A (all risks), while CIF remains at Clauses C; (3) DAT renamed to DPU (Delivered at Place Unloaded) - clarifies the seller's unloading obligation and allows any place, not just terminals; (4) Security requirements - enhanced provisions for security-related obligations and costs; (5) Own transport - explicit recognition that sellers (under D terms) and buyers (under F terms) may use their own transport rather than third-party carriers; (6) Explanatory notes - improved guidance for users. Trade finance implications: the FCA bill of lading option facilitates LC transactions for containerized cargo; enhanced CIP insurance affects cost calculations; clearer security provisions help allocate compliance costs. Documentary requirements should reflect these changes, particularly regarding transport documents under FCA and insurance certificates under CIP.",
    },
    {
      q: "How do Incoterms 2020 interact with the United Nations Convention on Contracts for the International Sale of Goods (CISG), and what happens when there are conflicts between Incoterm provisions and CISG rules?",
      a: "Incoterms and CISG operate in complementary but distinct spheres. CISG governs the formation of international sales contracts and the rights and obligations of buyer and seller regarding the goods, including conformity, remedies for breach, and passing of risk. Incoterms specifically address delivery obligations, risk transfer, and cost allocation. When both apply, Incoterms provisions on delivery and risk transfer generally prevail as specific contractual terms that modify CISG default rules. For example, CISG Article 67 provides default risk transfer rules, but an Incoterm specifying a different delivery/risk point will override this. However, Incoterms do not address: contract formation, goods conformity, remedies for breach, passing of property, or force majeure - these remain governed by CISG or applicable national law. Potential conflicts: if the sales contract contains provisions inconsistent with the chosen Incoterm, the specific contract terms typically prevail. Parties should ensure consistency between Incoterms, sales contract terms, and any applicable conventions. The relationship is generally harmonious, with Incoterms providing practical detail within the CISG framework.",
    },
    {
      q: "Explain the concept of 'named place' in Incoterms 2020 and its significance for different terms. What are the best practices for specifying the named place in trade contracts?",
      a: "The 'named place' in Incoterms identifies a specific location relevant to delivery, risk transfer, or cost allocation. Its significance varies by term: for F terms (FCA, FAS, FOB), the named place is where the seller delivers and risk transfers; for C terms (CFR, CIF, CPT, CIP), the named place is the destination to which the seller contracts carriage (but risk transfers earlier); for D terms (DAP, DPU, DDP), the named place is where the seller delivers and risk transfers. Best practices include: (1) Be specific - 'FCA Seller's Warehouse, 123 Industrial Road, Shanghai, China' rather than 'FCA Shanghai'; (2) Match the place to the term - for FOB, name a port; for FCA, name the precise delivery point; (3) Consider practical implications - can the seller actually deliver to the named place? (4) Align with transport arrangements - the named place should match where goods will actually be handed over; (5) For C terms, distinguish between the place of delivery (where risk transfers) and the named destination (where carriage ends); (6) Verify the named place is appropriate for customs and documentation purposes. Imprecise named places are a leading cause of Incoterms disputes.",
    },
    {
      q: "How do Incoterms 2020 address the seller's obligation to provide documents, and what are the implications for documentary credit transactions?",
      a: "Under Incoterms 2020, the seller's document obligations are specified in A6 of each rule. Common obligations include: commercial invoice (all terms); transport document appropriate to the mode and term; export license and customs documents; insurance document (CIF, CIP); and other documents specified in the contract. For documentary credits, alignment is crucial: (1) Transport documents - the LC should require documents consistent with the Incoterm; e.g., FOB/CIF require shipped on-board ocean bills of lading, while FCA/CPT may involve multimodal transport documents; (2) Insurance - CIF/CIP require insurance documents; LCs should specify coverage level consistent with the Incoterm (Clauses A for CIP, Clauses C for CIF minimum); (3) The new FCA provision allowing sellers to obtain on-board B/Ls addresses a practical LC issue; (4) Origin certificates, inspection certificates, and packing lists should be required as appropriate. Common issues: LCs requiring shipped B/Ls for EXW or FCA transactions (before the 2020 change); insurance requirements inconsistent with the Incoterm; document requirements impossible to fulfill given the delivery point. Parties should ensure LC terms align with the chosen Incoterm to avoid discrepancies.",
    },
  ],

  "Trade Finance Compliance & AML": [
    {
      q: "How do anti-money laundering (AML) regulations apply to trade finance transactions, and what are the specific red flags that banks should monitor in documentary credit and collection transactions?",
      a: "AML regulations require banks to apply customer due diligence, transaction monitoring, and suspicious activity reporting to trade finance. Specific red flags include: (1) Pricing anomalies - significantly over or under-invoiced goods compared to market prices; (2) Unusual shipping routes - goods routed through high-risk jurisdictions without commercial justification; (3) Inconsistent documentation - mismatches between goods descriptions, quantities, or values across documents; (4) Shell company involvement - parties with minimal business presence or unclear ownership; (5) Unusual payment patterns - requests for payment to third parties or in jurisdictions unrelated to the transaction; (6) Goods type concerns - dual-use goods, commodities prone to trade-based money laundering; (7) Repeat amendments - multiple amendments changing key terms; (8) Document irregularities - poor quality documents, inconsistent formats, or apparent alterations. Banks should implement automated screening for sanctions and PEPs, transaction monitoring systems calibrated for trade finance patterns, and trained staff capable of identifying anomalies. The FATF and Wolfsberg Group provide guidance on trade finance AML, emphasizing risk-based approaches given the document-intensive nature of trade transactions.",
    },
    {
      q: "What are the key sanctions compliance considerations for banks involved in trade finance, and how should banks handle transactions involving dual-use goods or parties in sanctioned jurisdictions?",
      a: "Sanctions compliance in trade finance requires: (1) Screening all parties - applicants, beneficiaries, shipping companies, ports, banks, and any other named parties against sanctions lists (OFAC, EU, UN, and local lists); (2) Goods screening - identifying sanctioned or controlled goods, including dual-use items that could have military applications; (3) Jurisdiction analysis - identifying connections to comprehensively sanctioned countries (e.g., North Korea, Iran) or sectoral sanctions programs; (4) End-use assessment - considering the ultimate use and end-user of goods. For dual-use goods, banks should: verify export licenses are in place; understand the stated end-use; assess whether the end-user and destination are consistent with legitimate use; and consider whether the goods could be diverted. For sanctioned jurisdictions, banks must determine whether the transaction is prohibited, requires a license, or falls within permitted categories. Even indirect involvement (e.g., goods transiting a sanctioned country) can create liability. Banks should maintain robust screening systems, clear escalation procedures, and documented decision-making processes. When in doubt, transactions should be escalated to compliance specialists and potentially declined.",
    },
    {
      q: "How does trade-based money laundering (TBML) differ from traditional money laundering, and what techniques are commonly used to launder money through international trade transactions?",
      a: "Trade-based money laundering exploits the complexity and volume of international trade to transfer value and obscure the origins of criminal proceeds. Unlike traditional money laundering through financial transactions, TBML uses trade transactions to move value. Common techniques include: (1) Over-invoicing - inflating the price of goods to transfer excess value to the seller; (2) Under-invoicing - understating prices to transfer value to the buyer; (3) Multiple invoicing - invoicing the same goods multiple times to justify multiple payments; (4) Falsely described goods - misrepresenting goods to justify prices inconsistent with actual shipments; (5) Phantom shipments - documenting shipments that never occur; (6) Black market peso exchange - using trade transactions to settle drug proceeds. TBML is challenging to detect because: trade transactions are inherently complex; banks see only documents, not physical goods; price verification is difficult for many goods; and the volume of legitimate trade provides cover. Detection requires: understanding typical pricing for goods traded; identifying unusual patterns; verifying the commercial logic of transactions; and cooperation between financial institutions, customs authorities, and law enforcement. The FATF has issued specific guidance on TBML risks and indicators.",
    },
    {
      q: "What are the documentary requirements for trade finance transactions under various regulatory frameworks, and how do banks ensure compliance while maintaining efficient transaction processing?",
      a: "Documentary requirements stem from multiple sources: (1) UCP 600/URDG 758/URC 522 - specify document examination standards and required documents for LCs, guarantees, and collections; (2) AML regulations - require customer identification documents, transaction records, and suspicious activity reports; (3) Sanctions regulations - require screening records and license documentation where applicable; (4) Export control regulations - require export licenses, end-user certificates, and destination control statements for controlled goods; (5) Customs regulations - require commercial invoices, packing lists, certificates of origin, and other customs documents; (6) Tax regulations - require proper invoicing and documentation for VAT/GST purposes. Banks ensure compliance through: automated document checking systems that verify required fields and consistency; sanctions and AML screening integrated into processing workflows; clear procedures for escalation and exception handling; training programs for trade finance staff; and regular audits of compliance processes. Efficiency is maintained through: straight-through processing for low-risk transactions; risk-based approaches that focus scrutiny on higher-risk transactions; and technology solutions that automate routine checks while flagging anomalies for human review.",
    },
    {
      q: "How do export credit agencies (ECAs) support trade finance, and what are the compliance and documentation requirements for ECA-backed transactions?",
      a: "Export Credit Agencies are government-backed institutions that support exports through insurance, guarantees, and direct lending. Major ECAs include US Ex-Im Bank, UK Export Finance, Euler Hermes (Germany), and COFACE (France). ECAs support trade finance by: (1) providing political risk insurance covering non-payment due to political events; (2) offering commercial risk insurance against buyer default; (3) guaranteeing bank loans to foreign buyers; (4) providing direct loans for large projects. Compliance requirements include: (1) OECD Arrangement - sets minimum interest rates, maximum repayment terms, and premium rates for officially supported export credits; (2) Anti-bribery compliance - ECAs require representations that no bribes were paid; (3) Environmental and social standards - many ECAs apply Equator Principles or similar standards; (4) Content requirements - goods must typically contain minimum domestic content; (5) Sanctions compliance - ECAs cannot support transactions involving sanctioned parties or destinations. Documentation requirements include: application forms detailing the transaction; buyer and country risk assessments; evidence of domestic content; environmental impact assessments for large projects; and anti-corruption declarations. ECA support can significantly enhance the bankability of transactions, particularly for emerging market buyers or large capital goods exports.",
    },
    {
      q: "What is the role of the Wolfsberg Group principles in trade finance compliance, and how do these principles guide banks in implementing effective AML controls?",
      a: "The Wolfsberg Group, an association of major global banks, has issued Trade Finance Principles providing guidance on AML controls for trade finance. Key elements include: (1) Risk-based approach - banks should assess and categorize trade finance risks based on customer, product, and geographic factors, applying enhanced due diligence to higher-risk transactions; (2) Customer due diligence - know your customer requirements apply to trade finance customers, with understanding of the customer's business, expected transaction patterns, and beneficial ownership; (3) Transaction screening - all parties and vessels should be screened against sanctions lists; goods should be screened for dual-use or controlled items; (4) Red flag indicators - the principles identify specific red flags for trade finance, including pricing anomalies, unusual routes, and documentary irregularities; (5) Training - staff should be trained to identify suspicious patterns specific to trade finance; (6) Record keeping - comprehensive records should be maintained for regulatory examination and investigation purposes. The principles recognize that banks deal with documents and cannot verify physical goods, but emphasize that banks should understand the commercial logic of transactions and identify anomalies. Implementation involves integrating these principles into policies, procedures, systems, and training programs.",
    },
    {
      q: "How do Basel III capital requirements affect trade finance, and what are the implications for banks' trade finance pricing and product offerings?",
      a: "Basel III capital requirements significantly impact trade finance through: (1) Credit Conversion Factors (CCFs) - off-balance sheet items like LCs and guarantees are converted to credit exposure equivalents; trade finance products generally receive favorable CCFs (20-50%) compared to other commitments; (2) Leverage ratio - the leverage ratio does not allow CCF reductions, meaning trade finance exposures are counted at full notional value, potentially constraining capacity; (3) Liquidity requirements - LCR and NSFR affect funding costs for trade finance assets; (4) Counterparty credit risk - exposure to bank counterparties in trade finance (confirming banks, etc.) consumes capital. Implications include: (1) Pricing pressure - capital costs are passed through to customers, increasing trade finance pricing; (2) Product mix shifts - banks may favor products with lower capital consumption; (3) Capacity constraints - leverage ratio limits may constrain trade finance volumes regardless of risk; (4) Emerging market impact - higher capital requirements for emerging market exposures may reduce availability. The ICC and banking industry have advocated for recognition of trade finance's low-risk characteristics, leading to some regulatory adjustments. Banks must carefully manage trade finance portfolios within capital constraints while maintaining service to clients.",
    },
    {
      q: "What are the key considerations for banks when financing goods subject to export controls, and how should dual-use goods transactions be handled?",
      a: "Export controls regulate goods, software, and technology that could contribute to weapons development, human rights abuses, or other harmful purposes. Key considerations include: (1) Classification - determining whether goods are controlled under relevant regimes (Wassenaar Arrangement, Nuclear Suppliers Group, Australia Group, MTCR) and national control lists; (2) License requirements - identifying whether an export license is required based on the item classification, destination, end-user, and end-use; (3) Red flags - indicators that goods may be diverted to prohibited end-users or uses, such as unusual technical specifications, reluctance to provide end-user information, or routing through transshipment points; (4) End-user verification - obtaining and verifying end-user certificates and conducting due diligence on the ultimate consignee; (5) Documentation - ensuring export licenses are valid and cover the specific transaction. For dual-use goods, banks should: understand the goods being financed and their potential applications; verify that required licenses are in place; assess the credibility of stated end-use; be alert to diversion indicators; and maintain records of due diligence performed. Banks are not expected to be export control experts but should have processes to identify controlled goods and escalate to specialists. Failure to comply with export controls can result in significant penalties and reputational damage.",
    },
    {
      q: "How do banks manage country risk in trade finance, and what factors influence country risk limits and pricing for trade finance transactions?",
      a: "Country risk in trade finance encompasses: (1) Transfer risk - the risk that a country restricts foreign exchange transfers, preventing payment even by willing buyers; (2) Political risk - risks from war, expropriation, government actions, or political instability; (3) Sovereign risk - risk of government default affecting state-owned buyers or guarantors; (4) Economic risk - macroeconomic instability affecting private sector ability to pay. Banks manage country risk through: (1) Country limits - aggregate exposure limits by country, often tiered by product type and tenor; (2) Risk assessment - ongoing evaluation of country conditions using internal analysis and external ratings; (3) Pricing - country risk premiums reflected in fees and margins; (4) Mitigation - use of ECA cover, political risk insurance, or confirmation by banks in lower-risk countries; (5) Tenor limits - shorter tenors for higher-risk countries. Factors influencing limits and pricing include: sovereign credit ratings; foreign exchange reserves and current account position; political stability and rule of law; historical payment experience; and specific sector or transaction characteristics. Trade finance often receives more favorable treatment than other exposures due to its self-liquidating nature and the security provided by underlying goods. Banks typically maintain country risk frameworks that integrate trade finance into overall country exposure management.",
    },
    {
      q: "What are the implications of digitalization and blockchain technology for trade finance compliance, and how might these technologies transform AML and sanctions compliance processes?",
      a: "Digitalization and blockchain offer significant potential for trade finance compliance: (1) Document digitization - electronic documents reduce fraud risk through better authentication and audit trails; platforms like SWIFT's Trade Services Utility and various blockchain initiatives enable digital document exchange; (2) Automated screening - AI and machine learning can enhance sanctions and AML screening, reducing false positives while improving detection of sophisticated evasion techniques; (3) Data analytics - analysis of large transaction datasets can identify patterns indicative of TBML or sanctions evasion; (4) Blockchain benefits - immutable records, shared visibility among authorized parties, smart contracts automating compliance checks, and reduced document fraud through cryptographic verification; (5) Digital identity - blockchain-based identity solutions could streamline KYC processes and enable trusted sharing of due diligence information. Challenges include: regulatory acceptance of digital documents and signatures; interoperability between different platforms; data privacy concerns; and the need for industry-wide adoption to realize network benefits. Initiatives like the Marco Polo Network, we.trade, and Contour are developing blockchain-based trade finance platforms with embedded compliance features. Regulators are increasingly supportive of digitalization, with UNCITRAL's Model Law on Electronic Transferable Records providing a legal framework for electronic trade documents.",
    },
  ],

  "International Trade Law & Conventions": [
    {
      q: "How does the United Nations Convention on Contracts for the International Sale of Goods (CISG) interact with letters of credit and other trade finance instruments in cross-border transactions?",
      a: "CISG governs the formation of international sales contracts and the rights and obligations of buyer and seller, but it does not directly govern trade finance instruments. The interaction occurs at several points: (1) Payment terms - CISG Article 54 requires the buyer to take steps and comply with formalities required for payment, including opening letters of credit; failure to open a required LC is a breach; (2) Document obligations - CISG Article 34 addresses the seller's obligation to hand over documents; this interacts with LC document requirements; (3) Risk of loss - CISG Articles 66-70 provide default rules on risk transfer, but Incoterms (commonly incorporated) typically override these; (4) Remedies - CISG remedies for breach (avoidance, damages, price reduction) are separate from LC payment obligations due to the independence principle; (5) Conformity of goods - CISG Article 35 requires goods to conform to the contract; non-conformity may give rise to claims but does not affect LC payment for compliant documents. The independence principle means that LC payment proceeds even if CISG remedies exist for non-conforming goods. Parties must understand that trade finance instruments operate independently of the sales contract governed by CISG, though both form part of the overall transaction structure.",
    },
    {
      q: "What are the key provisions of the UN Convention on International Bills of Exchange and International Promissory Notes, and why has this convention not achieved widespread adoption?",
      a: "The UN Convention on International Bills of Exchange and International Promissory Notes (1988) attempted to create uniform rules for international negotiable instruments, bridging differences between common law and civil law traditions. Key provisions include: (1) Scope - applies to instruments expressly designated as 'International Bills of Exchange (UNCITRAL Convention)' or 'International Promissory Notes (UNCITRAL Convention)'; (2) Form requirements - specifies required elements for valid instruments; (3) Transfer and negotiation - provides rules for endorsement and holder in due course status; (4) Liability of parties - defines obligations of drawer, acceptor, and endorsers; (5) Presentment and dishonor - establishes procedures for presentment and consequences of dishonor; (6) Limitation period - four-year limitation period for actions on the instrument. The convention has not achieved widespread adoption (only a few ratifications) because: (1) Opt-in requirement - instruments must be expressly designated, reducing practical utility; (2) Existing frameworks - well-established national laws (UK Bills of Exchange Act, US UCC) and the Geneva Uniform Laws already provide workable frameworks; (3) Complexity - the convention's attempt to bridge different legal traditions resulted in complex provisions; (4) Market preference - the trade finance market has developed around existing instruments and practices. The convention remains available but is rarely used in practice.",
    },
    {
      q: "How do the Hague-Visby Rules, Hamburg Rules, and Rotterdam Rules differ in their treatment of carrier liability, and what are the implications for cargo insurance and trade finance?",
      a: "These conventions govern carrier liability for cargo loss or damage during maritime transport: Hague-Visby Rules (most widely adopted): carrier liable for loss/damage unless due to excepted perils (including negligent navigation); package limitation of 666.67 SDR per package or 2 SDR per kg; one-year time bar for claims. Hamburg Rules: broader carrier liability, removing the negligent navigation defense; higher limits (835 SDR per package or 2.5 SDR per kg); two-year time bar; covers deck cargo and live animals. Rotterdam Rules (not yet in force): comprehensive multimodal coverage; even broader carrier liability; higher limits (875 SDR per package or 3 SDR per kg); two-year time bar; addresses electronic documentation. Trade finance implications: (1) Cargo insurance - the applicable convention affects the allocation of risk between carrier and cargo interests, influencing insurance coverage needs and claims recovery; (2) Bill of lading clauses - carriers incorporate convention limits into B/L terms; banks should understand these limitations; (3) Claims recovery - time bars affect the ability to recover from carriers, relevant for banks holding security over goods; (4) Document requirements - the Rotterdam Rules' provisions for electronic transport documents could facilitate trade finance digitalization. Banks and traders should understand which convention applies (typically determined by the B/L terms and the countries involved) to assess risk allocation properly.",
    },
    {
      q: "What is the legal framework governing international factoring, and how do the UNIDROIT Convention on International Factoring and the UN Convention on the Assignment of Receivables affect cross-border factoring transactions?",
      a: "International factoring involves the purchase of receivables arising from international sales. The legal framework includes: UNIDROIT Convention on International Factoring (Ottawa Convention, 1988): applies when the supplier and debtor are in different states; validates assignment of receivables even if the sales contract prohibits assignment; requires notice to the debtor for the factor to have priority; provides rules for the debtor's defenses and set-off rights. UN Convention on the Assignment of Receivables in International Trade (2001): broader scope covering all assignments, not just factoring; overrides contractual prohibitions on assignment; provides conflict of laws rules for priority among competing assignees; addresses future receivables and bulk assignments. Practical implications: (1) Anti-assignment clauses - both conventions validate assignments despite contractual prohibitions, protecting factors; (2) Debtor notification - notice requirements affect when the factor can collect directly from the debtor; (3) Priority rules - the UN Convention's priority rules provide certainty in competing claims scenarios; (4) Cross-border enforcement - conventions facilitate recognition of assignments across jurisdictions. Neither convention has achieved widespread ratification, so national laws often govern. Factors typically conduct legal due diligence on applicable laws and structure transactions to ensure valid, enforceable assignments. The conventions provide useful frameworks even where not directly applicable.",
    },
    {
      q: "How do international arbitration conventions (New York Convention, ICSID Convention) support dispute resolution in trade finance, and what are the advantages of arbitration over litigation for trade finance disputes?",
      a: "International arbitration is widely used for trade finance disputes, supported by: New York Convention (1958): provides for recognition and enforcement of foreign arbitral awards in 170+ contracting states; limited grounds for refusing enforcement (procedural irregularities, public policy, non-arbitrability); creates a more reliable enforcement framework than foreign court judgments. ICSID Convention: specifically for investor-state disputes; relevant for trade finance involving government entities or state-owned enterprises; awards are directly enforceable without local court review. Advantages of arbitration for trade finance include: (1) Neutrality - parties can choose a neutral forum rather than either party's home courts; (2) Expertise - arbitrators with trade finance expertise can be selected; (3) Enforceability - New York Convention provides superior cross-border enforcement compared to court judgments; (4) Confidentiality - arbitration proceedings are typically confidential, protecting commercial relationships; (5) Flexibility - parties can tailor procedures to suit the dispute; (6) Speed - arbitration can be faster than litigation in some jurisdictions; (7) Finality - limited grounds for appeal provide certainty. Trade finance contracts commonly include arbitration clauses specifying institutions like ICC, LCIA, or Singapore International Arbitration Centre. Banks should ensure arbitration clauses are properly drafted and consider the enforceability of awards in relevant jurisdictions.",
    },
    {
      q: "What are the key provisions of the UNCITRAL Model Law on Electronic Transferable Records, and how does it facilitate the digitalization of trade finance documents?",
      a: "The UNCITRAL Model Law on Electronic Transferable Records (MLETR, 2017) provides a legal framework for electronic equivalents of paper-based transferable documents such as bills of lading, bills of exchange, and promissory notes. Key provisions include: (1) Functional equivalence - an electronic transferable record meets legal requirements for a paper document if it contains the required information and uses a reliable method to identify the record and render it capable of being subject to control; (2) Control - the concept of 'control' replaces 'possession' for electronic records; a person has control if the system reliably establishes that person as the one to whom the record was issued or transferred; (3) Singularity - the system must ensure that only one person can have control at any time (preventing double-spending); (4) Integrity - the electronic record must remain complete and unaltered; (5) General reliability standard - methods used must be reliable and appropriate for the function. Trade finance implications: (1) Electronic bills of lading - MLETR enables legally valid electronic B/Ls that can be transferred and pledged like paper B/Ls; (2) Negotiable instruments - electronic bills of exchange and promissory notes become legally viable; (3) Platform development - provides legal certainty for blockchain and other platforms handling trade documents; (4) LC transactions - facilitates electronic presentation of documents under LCs. Countries adopting MLETR (including Singapore, Bahrain, and others) create legal certainty for digital trade finance. The UK's Electronic Trade Documents Act 2023 implements similar principles.",
    },
    {
      q: "How do bilateral and multilateral free trade agreements affect trade finance, particularly regarding rules of origin, tariff preferences, and documentary requirements?",
      a: "Free trade agreements (FTAs) significantly impact trade finance through: (1) Rules of origin - goods must meet origin criteria to qualify for preferential tariffs; this requires certificates of origin and supporting documentation that banks may need to verify or handle; (2) Tariff preferences - reduced or zero tariffs under FTAs affect the value of goods and thus the amount financed; banks should understand applicable tariff rates; (3) Documentary requirements - FTAs specify required origin documentation (certificates of origin, supplier declarations, origin statements on invoices); these documents may be required under LCs; (4) Cumulation rules - FTAs may allow materials from partner countries to count toward origin, affecting supply chain financing decisions; (5) Trade facilitation - many FTAs include trade facilitation provisions reducing customs delays and costs. Practical implications for trade finance: (1) LC document requirements should align with FTA documentation needs; (2) Banks financing goods should understand origin rules to assess tariff treatment; (3) Incorrect origin claims can result in penalties and duty recovery, affecting the transaction's economics; (4) Regional trade agreements (like RCEP, USMCA, EU agreements) create complex webs of preferential treatment that affect trade flows and financing patterns. Banks should have awareness of major FTAs affecting their clients' trade and ensure documentary requirements capture necessary origin documentation.",
    },
    {
      q: "What legal issues arise in ship financing and how do maritime liens, mortgages, and arrest procedures interact with trade finance secured on cargo or vessels?",
      a: "Ship financing involves complex legal issues intersecting with trade finance: Maritime liens - certain claims (crew wages, salvage, collision damage, necessaries) create liens on the vessel that take priority over registered mortgages; these arise by operation of law without registration. Ship mortgages - registered mortgages provide security for ship financing; priority generally follows registration date, but maritime liens rank ahead. Arrest procedures - creditors can arrest vessels to obtain security for maritime claims; arrest is available for various claims including cargo damage, unpaid freight, and mortgage enforcement. Interaction with trade finance: (1) Cargo financing - banks with security over cargo must understand that cargo may be subject to carrier's liens for freight and general average contributions; (2) Bill of lading as security - the B/L gives constructive possession of cargo, but physical possession may be complicated by vessel arrest or carrier's lien; (3) Vessel financing and trade - banks financing vessels must understand how maritime liens can prime their mortgage security; (4) Bunker financing - bunker suppliers may have maritime liens or statutory rights affecting vessel security; (5) Charter party financing - financing based on charter hire must consider the charterer's position if the vessel is arrested. Banks should conduct maritime legal due diligence, understand applicable flag state laws (which govern mortgage priority), and structure security arrangements considering maritime law complexities.",
    },
    {
      q: "How do sovereign immunity principles affect trade finance transactions involving state entities, and what waivers or structures can banks use to mitigate sovereign immunity risk?",
      a: "Sovereign immunity can prevent enforcement of claims against state entities, creating significant risk in trade finance. Key principles: (1) Absolute vs. restrictive immunity - most jurisdictions now apply restrictive immunity, allowing suits for commercial activities while maintaining immunity for governmental acts; (2) Commercial activity exception - trade finance transactions are generally considered commercial activities, potentially allowing suit; (3) Waiver - states can waive immunity by contract; (4) Execution immunity - even if suit is allowed, execution against state assets may be separately immune. Mitigation strategies include: (1) Express waivers - contracts should include comprehensive waivers of immunity from suit and execution; (2) Submission to jurisdiction - state entity should submit to jurisdiction of courts in a major financial center; (3) Arbitration clauses - arbitration awards may be more easily enforced under the New York Convention; ICSID awards have special enforcement status; (4) Asset identification - identify specific assets against which execution could proceed; (5) Guarantee structures - obtain guarantees from entities with clearly commercial character; (6) ECA cover - export credit agency insurance can cover political risks including sovereign non-payment; (7) Governing law - choose governing law from a jurisdiction with developed sovereign immunity jurisprudence. Banks should conduct careful legal analysis of the state entity's status, applicable immunity rules, and enforceability of waivers before extending trade finance to sovereign or state-owned counterparties.",
    },
    {
      q: "What are the legal considerations for trade finance in Islamic finance structures, and how do murabaha, musharaka, and other Sharia-compliant structures replicate conventional trade finance functions?",
      a: "Islamic trade finance must comply with Sharia principles prohibiting riba (interest), gharar (excessive uncertainty), and haram (prohibited) activities. Key structures include: Murabaha (cost-plus financing) - the bank purchases goods and sells them to the customer at a marked-up price payable in installments; replicates conventional trade financing with the bank taking title to goods; the markup replaces interest. Musharaka (partnership) - bank and customer jointly finance a trade transaction, sharing profits and losses according to agreed ratios; used for larger transactions requiring equity-like participation. Wakala (agency) - bank acts as agent to purchase goods on behalf of the customer for a fee; the customer provides funds upfront. Salam (forward sale) - advance payment for goods to be delivered later; used for commodity financing. Istisna (manufacturing contract) - financing for goods to be manufactured; payment can be deferred. Legal considerations include: (1) True sale requirement - murabaha requires genuine sale with bank taking ownership risk, not merely a financing arrangement; (2) Sharia board approval - structures must be approved by qualified Sharia scholars; (3) Documentation - contracts must accurately reflect the Islamic structure, not merely relabel conventional products; (4) Governing law - choice between Sharia law and conventional law affects enforceability; (5) Standardization - AAOIFI and IFSB standards provide guidance but interpretation varies. Banks offering Islamic trade finance need specialized expertise in structuring compliant transactions.",
    },
  ],
};

export default function TradeFinanceQA() {
  const navigate = useNavigate();

  const [domain, setDomain] = useState(Object.keys(domainData)[0]);
  const [question, setQuestion] = useState('');
  const [answer, setAnswer] = useState('');
  const [loading, setLoading] = useState(false);
  const [step, setStep] = useState('');

  const steps = [
    'Processing question',
    'Analyzing trade rules',
    'Searching knowledge base',
    'Generating expert answer'
  ];

  const handleSubmit = async () => {
    if (!question.trim()) return;

    setLoading(true);
    setAnswer('');
    setStep(steps[0]);

    let idx = 0;
    const interval = setInterval(() => {
      idx++;
      if (idx < steps.length) setStep(steps[idx]);
      else clearInterval(interval);
    }, 1500);

    try {
      const res = await fetch(`${BACKEND_URL}/api/lc/trade_qa`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          question: `${domain}: ${question}`
        })
      });

      const data = await res.json();
      clearInterval(interval);

      setStep('Completed');
      setAnswer(data.answer || 'No response received.');
    } catch (err) {
      clearInterval(interval);
      toast.error('Failed to fetch answer');
    }

    setLoading(false);
  };

  return (
    <Fragment>
      <div className="w-full p-6 space-y-6 card">

        {/* 🔙 Back */}
        <Button
          variant="ghost"
          className="flex items-center gap-2 w-fit"
          onClick={() => navigate('/dashboard')}
        >
          <ArrowLeft className="w-4 h-4" />
          Back to Dashboard
        </Button>

        {/* 🧠 Header */}
        <Card className="border border-primary/50 bg-primary/5">
          <CardHeader className="flex flex-row items-center gap-4">
            <MessageCircle className="w-8 h-8 text-primary" />
            <div>
              <CardTitle className="text-2xl">TradeFinance AI</CardTitle>
              <p className="text-sm text-muted-foreground italic">
                Ask questions on UCP 600, URDG 758, Incoterms 2020, AML & more
              </p>
            </div>
          </CardHeader>
        </Card>

        {/* 📘 Input Section */}
        <Card className="border border-primary/50 bg-primary/5">
          <CardContent className="space-y-6">

            {/* Domain */}
            <div>
              <MenuLabel>Select Domain</MenuLabel>
              <select
                value={domain}
                onChange={(e) => {
                  setDomain(e.target.value);
                  setQuestion('');
                }}
                className="w-full border rounded px-3 py-2 dark:bg-primary-clarity"
              >
                {Object.keys(domainData).map((d) => (
                  <option key={d}>{d}</option>
                ))}
              </select>
            </div>

            {/* Built-in Questions */}
            <div>
              <MenuLabel>Built-in Questions</MenuLabel>
              <select
                className="w-full border rounded px-3 py-2 dark:bg-primary-clarity"
                onChange={(e) => setQuestion(e.target.value)}
                defaultValue=""
              >
                <option value="">-- Select or type your own --</option>
                {domainData[domain].map((q, i) => (
                  <option key={i} value={q.q}>{q.q}</option>
                ))}
              </select>
            </div>

            {/* Question */}
            <div>
              <MenuLabel>Your Question</MenuLabel>
              <Textarea
                rows={5}
                value={question}
                onChange={(e) => setQuestion(e.target.value)}
                placeholder="Ask a trade finance question..."
              />
            </div>

            {/* Submit */}
            <Button
              onClick={handleSubmit}
              disabled={loading}
              className="w-full md:w-1/2 mx-auto flex items-center gap-2"
            >
              {loading ? (
                <>
                  <Loader2 className="animate-spin w-4 h-4" />
                  {step}
                </>
              ) : (
                <>
                  <Send className="w-4 h-4" />
                  Get Answer
                </>
              )}
            </Button>
          </CardContent>
        </Card>

        {/* 📊 Answer */}
        {answer && (
          <Card className="border border-primary/50">
            <CardHeader>
              <CardTitle>AI Response</CardTitle>
            </CardHeader>
            <CardContent className="space-y-3 text-gray-700">
              {answer
                .replace(/\*\*/g, '')
                .split('\n')
                .map((line, idx) => (
                  <p key={idx}>{line.trim()}</p>
                ))}
            </CardContent>
          </Card>
        )}

        {/* Footer */}
        <div className="text-center text-xs text-muted-foreground">
          🔐 RAG-powered Trade Finance Knowledge Base · Multi-hop Reasoning
        </div>
      </div>
    </Fragment>
  );
}
